name: bookly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.7.0
  go_router: ^14.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  js: ^0.7.0
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
      -  assets/images/
  fonts:
    - family: GTSectraFine
      fonts:
        - asset: assets/fonts/GTSectraFineRegular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic