name: bookly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
      -  assets/images/
fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
      - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
        style: italic
  - family: GT Sectra Fine
    fonts:
      - asset: assets/fonts/GT Sectra Fine Regular.ttf